server:
  port: 8070
  servlet.context-path: /api/v1

# Logging config
logging:
  level.root: DEBUG

##Spring security
#spring.security.user.name=test
#spring.security.user.password=test

# H2 Database Configuration
spring:
  # Spring security
  #    security:
  #        user:
  #            name: test
  #            password: test
  datasource:
    url: jdbc:h2:file:/data/UserRegistrationOrchestration
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
  #Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none #update
    show-sql: true
  #H2 Console (optional) - http://localhost:8070/api/v1/h2-console
  h2:
    console:
      enabled: true
      path: /h2-console

# Conductor server configurations
#conductor:
##  api.url: http://localhost:8070/api/v1/conductor
#  db:
#    type: h2  # Specify H2 database for Conductor
#  task:
#    worker-poll-interval: 100  # Task poll interval in ms
#    worker-poll-count: 10      # Number of tasks to poll